services:
  app:
    container_name: brain-ag-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=farm_db
    depends_on:
      - postgres
    networks:
      - farm-network

  postgres:
    container_name: brain-ag-postgres
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=farm_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - farm-network

volumes:
  postgres_data:

networks:
  farm-network:
    driver: bridge